server:
  port: 8762

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #通过服务实例名直接转发路径
      routes:
      - id: user
        uri: lb://geek-user
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=1 #转发后路径去掉、/user

        # redis限流 ， filter名称必须是RequestRateLimiter
        - name: RequestRateLimiter
          args:
            # 使用SpEL名称引用Bean，与上面新建的RateLimiterConfig类中的bean的name相同
            key-resolver: '#{@remoteAddrKeyResolver}'
            # 每秒最大访问次数
            redis-rate-limiter.replenishRate: 20
            # 令牌桶最大容量
            redis-rate-limiter.burstCapacity: 20

        # 熔断降级配置
        - name: Hystrix
          args:
            name : default
            fallbackUri: 'forward:/defaultfallback'

         # hystrix 信号量隔离，2秒后自动超时
        hystrix:
          command:
            default:
              execution:
                isolation:
                  strategy: SEMAPHORE
                  thread:
                    timeoutInMilliseconds: 2000
          shareSecurityContext: true


  redis:
      host: 172.16.54.183
      port: 6379
      password: '!RE%^E332^3ZDWEwwwe7839$%*&'
eureka:
  instance:
    prefer-ip-address: true #ip注册
    instanceId: ${spring.cloud.client.ip-address}:${server.port} #ip显示
    lease-renewal-interval-in-seconds: 10 #租期更新时间间隔
    lease-expiration-duration-in-seconds: 10 #租期到期时间
    appname: gateway
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/